[package]
name = "app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Baillissime application binary"
repository = "https://github.com/gdraznieks/Baillissime"
readme = "../../README.md"
keywords = ["baillissime"]
categories = ["command-line-utilities"]

[dependencies]
app-core = { path = "../core" }
anyhow.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
